services:
  - type: web
    name: detecteur-accords
    env: python
    buildCommand: pip install -r requirements.txt && pip uninstall numba -y 2>/dev/null; true
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 180
    plan: free
    envVars:
      - key: NUMBA_DISABLE_JIT
        value: "1"
